export interface ChatMessage {
  id: string;
  role: "user" | "assistant" | "system";
  type:
    | "text"
    | "tool_use"
    | "tool_result"
    | "thinking"
    | "permission_request"
    | "ask_question"
    | "plan_proposal"
    | "stopped"
    | "memory_recall"
    | "error";
  content: string;
  toolName?: string;
  toolCallId?: string;
  toolInput?: string;
  isError?: boolean;
  timestamp: number;
  /** For permission_request messages */
  permissionId?: string;
  permissionInput?: Record<string, unknown>;
  permissionResolved?: boolean;
  permissionAllowed?: boolean;
  /** Custom deny reason the user typed when denying the tool (optional). */
  permissionMessage?: string;
  /** For ask_question messages */
  askId?: string;
  askQuestions?: AskQuestionItem[];
  askResolved?: boolean;
  /** For plan_proposal messages (fires when Claude calls ExitPlanMode). */
  planId?: string;
  planContent?: string;
  planResolved?: boolean;
  /** How the user resolved the plan — drives the "Approved"/"Rejected" badge. */
  planOutcome?: "approved_accept_edits" | "approved_default" | "approved_auto" | "rejected";
  planMessage?: string;
  /** For memory_recall messages — paths the SDK auto-memory supervisor surfaced into this turn. */
  memoryRecallPaths?: string[];
  /** Recall mode reported by the SDK: full file bodies vs. distilled synthesis. */
  memoryRecallMode?: "select" | "synthesize";
}

export type ClaudeStatus =
  | "disconnected"
  | "connecting"
  | "idle"
  | "thinking"
  | "tool_running"
  | "awaiting_permission"
  | "awaiting_input";

export interface ActiveToolInfo {
  name: string;
  callId: string;
}

export interface AskQuestionItem {
  question: string;
  header: string;
  options: Array<{ label: string; description: string; preview?: string }>;
  multiSelect: boolean;
}

/**
 * Answers sent back for an ask_question. Single-select questions return a
 * string; multi-select return a string array. The special key form
 * `"__other__:<questionIndex>"` carries a free-text answer when the user
 * picks "Other" (auto-generated by the UI).
 */
export type AskQuestionAnswers = Record<string, string | string[]>;

export interface ChatSession {
  sessionId: string;
  display: string;
  timestamp: number;
}

export interface FileEntry {
  name: string;
  path: string;
  directory: boolean;
  size: number;
  /** Last modified time (ms since epoch). 0 if unavailable. */
  mtime?: number;
}
