import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettierConfig from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Compiled JS artifacts (generated by tsc, not hand-written)
    "server.js",
    "src/lib/auth-server.js",
  ]),
  // Disable ESLint rules that conflict with Prettier (must be last).
  prettierConfig,
]);

export default eslintConfig;
