import { chmod, mkdir, writeFile } from "fs/promises";
import { join } from "path";
import { homedir } from "os";
import { extractSession, unauthorized } from "@/lib/auth-server";
import { loadCredentials, registerMcpServer } from "@/lib/google-custom-config";

/**
 * Generate a one-shot setup script the user runs in an in-browser terminal
 * to complete the Google OAuth flow.
 *
 * The script pins WORKSPACE_MCP_PORT to 8765 (avoiding a collision with the
 * chat app's own PORT=3100), points workspace-mcp's OAuth redirect at our
 * public /chat/api/google-custom/oauth-callback (which proxies back to
 * localhost:8765 internally), and prints the authorization URL to stdout
 * for the user to open in a new browser tab.
 *
 * The MCP server entry in ~/.claude.json is registered immediately so a
 * subsequent chat query that invokes a Google tool reuses the credentials
 * workspace-mcp caches after auth — no second click-through needed.
 */

const SETUP_DIR = join(homedir(), ".claude", "custom-google-workspace");
const SETUP_SCRIPT = join(SETUP_DIR, "setup.sh");
const CALLBACK_PATH = "/chat/api/google-custom/oauth-callback";

function resolvePublicBase(request: Request): string {
  // Prefer the Host header (respects whatever reverse proxy is in front of
  // us); fall back to NEXT_PUBLIC_API_ORIGIN only for local dev.
  const host = request.headers.get("x-forwarded-host") || request.headers.get("host");
  const proto =
    request.headers.get("x-forwarded-proto") ||
    (host && !host.startsWith("localhost") ? "https" : "http");
  if (host) return `${proto}://${host}`;
  return (process.env.NEXT_PUBLIC_API_ORIGIN || "http://localhost:3100").replace(/\/+$/, "");
}

function shellQuote(raw: string): string {
  // POSIX-safe single-quote escape. Used for env values in the generated
  // script so credentials can contain any printable chars without breaking
  // bash parsing.
  return "'" + raw.replace(/'/g, "'\\''") + "'";
}

export async function POST(request: Request): Promise<Response> {
  if (!extractSession(request)) return unauthorized();

  const creds = await loadCredentials();
  if (!creds) {
    return Response.json(
      { error: "No credentials configured. Save client_id + client_secret first." },
      { status: 400 },
    );
  }

  const base = resolvePublicBase(request);
  const redirectUri = `${base}${CALLBACK_PATH}`;

  // Register the MCP entry in ~/.claude.json now so the agent SDK picks
  // it up on the next chat query regardless of whether the terminal
  // session stays open after auth completes.
  try {
    await registerMcpServer(creds);
  } catch (err) {
    return Response.json(
      {
        error: `Failed to register MCP entry: ${err instanceof Error ? err.message : String(err)}`,
      },
      { status: 500 },
    );
  }

  const script = `#!/usr/bin/env bash
# Generated by /chat/api/google-custom/setup-script — do not edit by hand.
# Re-generated on every "Run Setup in Terminal" click.
set -euo pipefail

export GOOGLE_OAUTH_CLIENT_ID=${shellQuote(creds.clientId)}
export GOOGLE_OAUTH_CLIENT_SECRET=${shellQuote(creds.clientSecret)}
export WORKSPACE_MCP_PORT=8765
export WORKSPACE_MCP_HOST=127.0.0.1
export WORKSPACE_EXTERNAL_URL=${shellQuote(base)}
export GOOGLE_OAUTH_REDIRECT_URI=${shellQuote(redirectUri)}

cat <<'BANNER'
== Google Workspace OAuth setup ==

Make sure this URL is listed under "Authorized redirect URIs" in your
Google OAuth client (https://console.cloud.google.com/apis/credentials):

BANNER
printf '    %s\\n\\n' "$GOOGLE_OAUTH_REDIRECT_URI"
cat <<'BANNER'
When the server prints an https://accounts.google.com/... URL below,
open it in a new browser tab and sign in. Google will redirect you back
to the chat, which forwards the code to this process. Watch for a
"Credentials stored" message here, then close this terminal.

BANNER

exec uvx workspace-mcp --single-user --tool-tier core
`;

  try {
    await mkdir(SETUP_DIR, { recursive: true });
    await writeFile(SETUP_SCRIPT, script, "utf-8");
    try {
      await chmod(SETUP_SCRIPT, 0o700);
    } catch {
      /* best-effort on non-POSIX */
    }
  } catch (err) {
    return Response.json(
      {
        error: `Failed to write setup script: ${err instanceof Error ? err.message : String(err)}`,
      },
      { status: 500 },
    );
  }

  return Response.json({
    scriptPath: SETUP_SCRIPT,
    callbackUrl: redirectUri,
  });
}
